### PR TITLE
Match upstream

### PR DESCRIPTION
**Pull request by clamburger**
With these last few changes we should now match upstream!

### CODE REVIEW

**Comment by mkopinsky** [comment]
Thanks for all your work! I'd like to review this side-by-side with upstream before officially releasing.

One thing we should address (either by deleting or updating) is that the ZxcvbnTest is still skipped.

**Comment by mkopinsky** [comment]
re that broken Travis build - it's a one-line workaround to get around that failure in PHP 5.5, but I think we should just support 5.6+. 5.5 has been unsupported for almost 2 years.

**Comment by clamburger** [comment]
@mkopinsky I think this is done in terms of matching upstream and is ready to merge. I've tested against the top 1 million passwords from the rockyou password list and haven't found any further discrepancies.

**Comment by mkopinsky** [comment]
Can you add the scripts or documentation on how you did that comparison? I think that would be a useful tool for the future when/if upstream releases a new version.

**Pull request merged**
